version: "3.0"

services:
  redis_stack:
    container_name: redis_stack
    hostname: redis-stack
    image: redis/redis-stack:6.2.6-v0
    restart: unless-stopped
    ports:
      - "4001:8001"

  experience_graph:
    container_name: experience_graph
    hostname: experience-graph
    image: memgraph/memgraph-platform:2.6.1-memgraph2.5.0-lab2.4.0
    tty: true
    ports:
      - "4002:3000"

  submissions_graph:
    container_name: submissions_graph
    hostname: submissions-graph
    image: memgraph/memgraph-platform:2.6.1-memgraph2.5.0-lab2.4.0
    tty: true
    ports:
      - "4003:3000"

  calculator_service:
    container_name: calculator_service
    hostname: calculator-service
    image: cypherflow/calculator_service
    build: ./CalculatorService
    restart: unless-stopped
    volumes:
      - ../../src/.:/app/lib/Cypherflow/.
    depends_on:
      - redis_stack
      - experience_graph
      - submissions_graph

  web_service:
    container_name: web_service
    hostname: web-service
    image: cypherflow/web_service
    build: ./WebService
    restart: unless-stopped
    depends_on:
      - calculator_service
    ports:
      - "4000:4000"
